### ISSUE TITLE
Handle no gamepad situations more elegantly

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#11]
ttd

**Comment by benmoran56** [comment]
What kind of crash are you seeing? On my machines it works as expected:

./fightstick.sh 
$ No FightStick detected. Please attach and try again!

**Comment by calexil** [comment]
I mean.. we dont have a loop checking for a stick and showing missing.png until it gets connected

this is ttd

**Comment by benmoran56** [comment]
Ah, I see. If we do full hot-plug suport, it will be a little work involved. This is because the controller events need to all be added/removed on demand when a controller is added/removed. It's not hard, but the current code base is very simple. We'll have to isolate things a little better at that point.

I vote that we leave this one for later. The other features will be easer to add and reason about while the codebase is still simple.

**Comment by calexil** [comment]
I have decided this isn;t really a bug.

I am working on adding a delay to the sys exit, and tryin to figure out how to display the missing image

**Comment by calexil** [comment]
Don't worry about this item @benmoran56 

I am not skilled enough to sort out the custom button mapping, so try and start tackling that one.

I'm streaming fixing this issue live https://twitch.tv/calexil   in case you're bored

**Comment by calexil** [comment]
if len(controllers) > 0:
    fightstick = controllers[0]
    fightstick.open()
elif len(controllers) <= 0:
    print("No FightStick detected. Please reconnect and try again!")
    time.sleep(3)
    sys.exit(1)


I want this to somehow change

missing_sprite.visible = False

to
missing_sprite.visible = True

but it just wont work

**Comment by benmoran56** [comment]
Hey, sorry I missed your stream. We've got some time zone issues to deal with I think.
This looks like a simple thing to solve, but it's going to require a big refactor to encapsulate the current code. The reason is because the current code is basically serial:  it goes from top to bottom, and wires up all of the input event stuff as it goes. The decorators (@thing.event) are essentially setting up the events to fire. The problem is that if there is no controller attached, then we don't really want/need most of the code to execute. Instead, we want a smaller version to run that essentially only loads up a sprite. 

If you're OK with me making some drastic changes, I can do this. It won't take long, but it will change up the look of the program a bit.
