### ISSUE TITLE
My Gamepad was not detected!

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#44]
My Gamepad Make:
Pdp Rock Candy

My Gamepad Model:
wired xbox 360

**Comment by benmoran56** [comment]
We will need to add an SDL2 controller mapping to support this.  This tool looks easy to use and will give us the mapping we need to add:
http://generalarcade.com/gamepadtool/

It should be the same mapping as an XBOX 360 controller, so alternatively, if we find out the device's GUID, we can add it manually. You can find that from the FightstickDisplay directory like this:
```
~/FightstickDisplay $ python
...
import pyglet

joystick = pyglet.input.get_joysticks()[0]
print(joystick.device.get_guid())

>>> 050000004c050000c405000000810000
```

**Comment by calexil** [comment]
>>> print(joystick.device.get_guid())
030000006f0e00001f01000000010000



https://github.com/calexil/FightstickDisplay/commit/cb5b3e42cd113684782a0ea5a908d237f8508bcf

**Comment by benmoran56** [comment]
Awesome. I am going to do a little work to make this easier to handle in the future.
There is already a method available to add new mappings from a text file, in SDL2 format:
```pyglet.input.gamecontroller.add_mappings_from_file("filename")```
There is the popular community mapping database of all these mappings here:
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

We could add a check for this file on startup, so that users can drop in new mappings as a text file. Some games already check for this on startup. In addition, there is an environmental variable that can be set that contains the mappings, which I believe Steam does (and many SDL2 games check for).

**Comment by calexil** [comment]
good idea
